name: Switch production instance

on:
  workflow_dispatch:

jobs:
  switch-instance:
    runs-on: "0" # change to "dev"
    steps:
      - name: Install jq (yq)
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: yc setup
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true

      - name: Get active
        id: active-info
        run: echo "active=$(yc alb backend-group get production | yq '.["http"]["backends"][0]["backend_weight"]')" >> "$GITHUB_OUTPUT" # change "production" to <backend-group name>

      - name: if secondary active
        if: ${{ steps.active-info.outputs.active == 0 }}
        run: | # need to change instance name in FIRST string to "primary" instance AND rename instances, backend group names, names (ex. primary | secondary)
          yc compute instance stop prod-2 && yc compute instance update prod-2 --memory 12 --cores 6 && yc compute instance start prod-2
          sleep 120
          yc alb backend-group update-http-backend --backend-group-name production --name primary --weight 100 && yc alb backend-group update-http-backend --backend-group-name production --name secondary --weight 0
          sleep 180
          yc compute instance stop prod-2 && yc compute instance update prod-2 --memory 4 --cores 2 && yc compute instance start prod-2

      - name: if primary active
        if: ${{ steps.active-info.outputs.active == 100 }}
        run: | # need to change instance name in LAST string to "secondary" instance AND rename instances, backend group names, names (ex. primary | secondary)
          yc compute instance stop prod-2 && yc compute instance update prod-2 --memory 12 --cores 6 && yc compute instance start prod-2
          sleep 120
          yc alb backend-group update-http-backend --backend-group-name production --name secondary --weight 100 && yc alb backend-group update-http-backend --backend-group-name production --name primary --weight 0
          sleep 180
          yc compute instance stop prod-2 && yc compute instance update prod-2 --memory 4 --cores 2 && yc compute instance start prod-2
